"""1234

Revision ID: 29eeb07e407e
Revises: 7c22e733795b
Create Date: 2022-12-25 20:42:26.531309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eeb07e407e'
down_revision = '7c22e733795b'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
