"""ooooooooo

Revision ID: 5ca6c4c8d2c7
Revises: 6e7b5b6a909c
Create Date: 2022-12-27 22:35:34.498673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca6c4c8d2c7'
down_revision = '6e7b5b6a909c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=512), nullable=True))

    # ### end Alembic commands ###
