"""ooooooooo

Revision ID: 6e7b5b6a909c
Revises: ddd278afebaf
Create Date: 2022-12-27 22:31:55.243789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7b5b6a909c'
down_revision = 'ddd278afebaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
