"""1234

Revision ID: 7c22e733795b
Revises: 7e849e8b0090
Create Date: 2022-12-25 20:40:10.419533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c22e733795b'
down_revision = '7e849e8b0090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
