"""1234

Revision ID: bde013ec0760
Revises: 1fc50670b8f1
Create Date: 2022-12-25 20:49:07.997892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde013ec0760'
down_revision = '1fc50670b8f1'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
